//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPortalv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProgramCours
    {
        public string programID { get; set; }
        public string courseID { get; set; }
        public Nullable<int> courseUnits { get; set; }
        public Nullable<int> courseLevel { get; set; }
    
        public virtual tblProgram tblProgram { get; set; }
    }
}
