//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPortalv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsignUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblsignUp()
        {
            this.tblStudentCourses = new HashSet<tblStudentCours>();
        }
    
        public string fullName { get; set; }
        public string matricNo { get; set; }
        public string password { get; set; }
        public string programID { get; set; }
        public Nullable<int> sLevel { get; set; }
        public string DOB { get; set; }
        public string email { get; set; }
    
        public virtual tblProgram tblProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentCours> tblStudentCourses { get; set; }
    }
}
